# Generated by Django 3.0.2 on 2020-02-06 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=40)),
                ('buildingNumber', models.IntegerField()),
                ('apartamentNumber', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefon', models.IntegerField(blank=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('adresEmail', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.IntegerField(blank=True, unique=True)),
                ('opis', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=150)),
                ('eventDate', models.DateTimeField()),
                ('pubDate', models.DateField()),
                ('tresc', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=150)),
                ('iloscMiejsc', models.IntegerField()),
                ('cenaBiletu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ManyToManyField(to='eventapp.User')),
            ],
        ),
    ]
