# Generated by Django 3.0.2 on 2020-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20200207_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=150, verbose_name='Chapter numberrrr'),
        ),
    ]
