# Generated by Django 3.0.2 on 2020-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20200209_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cenaBiletu',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cena Biletu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(verbose_name='Data Eventu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=150, verbose_name='Nazwa eventu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='iloscMiejsc',
            field=models.IntegerField(verbose_name='Maksymalna ilość uczestników'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Lokalizacja Eventu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tresc',
            field=models.CharField(max_length=2000, verbose_name='Opis Eventu'),
        ),
    ]
