# Generated by Django 3.0.2 on 2020-02-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0004_auto_20200209_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30, verbose_name='Imie')),
                ('nazwisko', models.CharField(max_length=30, verbose_name='Nazwisko')),
                ('adresEmail', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefon', models.IntegerField(blank=True, unique=True, verbose_name='Telefon')),
                ('opis', models.CharField(max_length=2000, verbose_name='Opis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
